cask_args appdir: "/Applications"

brew "ansible"
brew "jq"
brew "tmux"
brew "curl"
brew "wget"
brew "graphviz"
brew "gnuplot"
brew "iperf"
brew "autossh"
brew "mas"
brew "anyenv"
brew "python3"

cask "alfred"
cask "synergy"
cask "bettertouchtool"
cask "google-chrome"
cask "google-drive-file-stream"
cask "google-japanese-ime"
cask "intellij-idea"
cask "iterm2"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "visual-studio-code"
cask "skype"
cask "slack"
cask "krisp"

mas "Magnet", id: 441258766
mas "Line", id: 539883307
mas "Evernote", id: 406056744
mas "Microsoft Word", id: 462054704
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
#Office365

